# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb-api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date_modified',
        ),
    ]
